-- AlterTable
ALTER TABLE `systemsetting` ADD COLUMN `academicYearEnd` DATETIME(3) NULL,
    ADD COLUMN `academicYearStart` DATETIME(3) NULL,
    ADD COLUMN `allowPartialPayment` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `currentAcademicYear` VARCHAR(191) NULL,
    ADD COLUMN `defaultTemplate` TEXT NULL,
    ADD COLUMN `documentCategories` TEXT NULL,
    ADD COLUMN `enableAutoPenalty` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `enableEmailNotifications` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `enableMandatoryContribution` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `enableSMSNotifications` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `minimumMeetingsPerYear` INTEGER NULL,
    ADD COLUMN `monthlyContributionAmount` DOUBLE NULL,
    ADD COLUMN `notificationDaysBeforeMeet` INTEGER NULL,
    ADD COLUMN `paymentBasis` VARCHAR(191) NULL,
    ADD COLUMN `paymentDueDays` INTEGER NULL,
    ADD COLUMN `penaltyGracePeriodDays` INTEGER NULL,
    ADD COLUMN `penaltyRateLate` DOUBLE NULL,
    ADD COLUMN `penaltyRatePerAbsence` DOUBLE NULL,
    ADD COLUMN `projectContributionMinimum` DOUBLE NULL,
    ADD COLUMN `quorumPercentage` INTEGER NULL,
    ADD COLUMN `senderName` VARCHAR(191) NULL,
    ADD COLUMN `smsApiKey` VARCHAR(191) NULL,
    ADD COLUMN `systemEmail` VARCHAR(191) NULL,
    ADD COLUMN `systemName` VARCHAR(191) NULL,
    ADD COLUMN `systemPhone` VARCHAR(191) NULL,
    ADD COLUMN `updatedById` INTEGER NULL,
    MODIFY `value` TEXT NULL;

-- AddForeignKey
ALTER TABLE `SystemSetting` ADD CONSTRAINT `SystemSetting_updatedById_fkey` FOREIGN KEY (`updatedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
